const GET_PLANS_BENEFITS = "GET_PLANS_BENEFITS";
const GET_BENEFITS = "GET_BENEFITS";
const GET_STATES = "GET_STATES";
const GET_LOCALITIES = "GET_LOCALITIES";

export { GET_PLANS_BENEFITS, GET_BENEFITS, GET_STATES, GET_LOCALITIES };
